project_name: repo-beaver

builds:
  - id: repo-beaver
    main: ./cmd/repo-beaver/main.go
    binary: repo-beaver
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  
archives:
  - format: tar.gz
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    files:
      - "{{ .Binary }}"

    format_overrides:
      - goos: windows
        format: zip
    
   
    
release:
  github:
    owner: deepdotdev013
    name: repo-beaver